language: haskell
ghc: 7.8 # Only used for Cabal

branches:
  only:
    - master
    - axioms

sudo: false

addons:
  apt:
    packages:
    - ocaml
    - camlidl
    - libgmp-dev

cache:
  apt: true
  directories:
  - $HOME/.stack
  - .stack-work

env:
  global:
  - STACK=0.1.5.0
  - SMT=z3
  - GHC=ghc-7.10.2
  matrix:
  - TESTS=Unit/
  - TESTS=Benchmarks/text
  - TESTS=Benchmarks/bytestring
  - TESTS=Benchmarks/esop
  - TESTS=Benchmarks/vect-algs
  - TESTS=Benchmarks/icfp*

 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour

install:
 - scripts/travis install_smt "$SMT"
 - scripts/travis install_stack "$STACK"
 - scripts/travis configure_stack "$GHC"
 - scripts/travis setup_ghc
 - scripts/travis install_dependencies

script:
 - scripts/travis do_build && scripts/travis do_test "$TESTS" "$SMT"

after_failure:
 - scripts/travis dump_fail_logs

notifications:
  slack:
    rooms:
      secure: CPaI+XVTUSM9gLQefB8zSXazawNIaUnClS7FwaujPfM37hNBm5UIoiC80KBEe0KZKBr+Gt/LWq0zv506Zl/vILuPpVmfSi2BQ8zyyKCBbUrE/E0uBTjmT7wjaITf/mn3mqiLLcHbAVXI1bn7HzVvAq4S4eIpttgCapF7pbMhZCk=
    on_success: change
    on_failure: always
    on_start: never
