language: sh

env:
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Unit/pos
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Unit/neg
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Unit/crash
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Benchmarks/text
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Benchmarks/bytestring
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Benchmarks/esop
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Benchmarks/vector-algorithms
 - CABALVER=1.20 GHCVER=7.8.4 SMT=cvc4 TESTS=Unit/pos
 - CABALVER=1.20 GHCVER=7.8.4 SMT=cvc4 TESTS=Unit/neg
 - CABALVER=1.20 GHCVER=7.8.4 SMT=cvc4 TESTS=Unit/crash
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Unit/icfp_pos
 - CABALVER=1.20 GHCVER=7.8.4 SMT=z3 TESTS=Unit/icfp_neg
 - CABALVER=1.22 GHCVER=7.10.1 SMT=z3 TESTS=Unit/pos
 - CABALVER=1.22 GHCVER=7.10.1 SMT=z3 TESTS=Unit/neg
 - CABALVER=1.22 GHCVER=7.10.1 SMT=z3 TESTS=Unit/crash
 # ugh... Classify.hs is too slow and makes travis think the build is stalled
 # - TESTS=hscolour


before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH="$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
 - scripts/travis install_ocaml
 - scripts/travis setup_cabal
 - scripts/travis clone_fixpoint
 - scripts/travis install_smt "$SMT"

install:
 - scripts/travis install_cabal_deps

script:
 - scripts/travis do_build
 - scripts/travis do_test "$TESTS" "$SMT" && scripts/travis test_source_pkg

after_failure:
 - scripts/travis dump_fail_logs

